# AIG230 NLP (Week 3 Lab) — Notebook 1: Text Representation

This notebook focuses on **turning raw text into numeric features** you can use in real-world ML systems.

You will build:
- a clean **train/test split**
- **Bag-of-Words** (binary and count)
- **Document-Term Matrix** (DTM)
- **TF-IDF** (with n-grams)
- **Hashing trick** (production-friendly)
- basic **retrieval** (cosine similarity) and a **baseline classifier**
- model **persistence** (save/load)

In [22]:
!pip install numpy pandas scikit-learn

Requirement already satisfied: numpy in /Users/andy/Documents/aig230_NLP/aig230-lab03-andy/.venv/lib/python3.9/site-packages (2.0.2)
Requirement already satisfied: pandas in /Users/andy/Documents/aig230_NLP/aig230-lab03-andy/.venv/lib/python3.9/site-packages (2.3.3)
Requirement already satisfied: scikit-learn in /Users/andy/Documents/aig230_NLP/aig230-lab03-andy/.venv/lib/python3.9/site-packages (1.6.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/andy/Documents/aig230_NLP/aig230-lab03-andy/.venv/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/andy/Documents/aig230_NLP/aig230-lab03-andy/.venv/lib/python3.9/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/andy/Documents/aig230_NLP/aig230-lab03-andy/.venv/lib/python3.9/site-packages (from pandas) (2025.3)
Requirement already satisfied: scipy>=1.6.0 in /Users/andy/Documents/aig230_NLP/aig230-lab03-andy/.venv/lib/python3.9/site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /Users/andy/Documents/aig230_NLP/aig230-lab03-andy/.venv/lib/python3.9/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/andy/Documents/aig230_NLP/aig230-lab03-andy/.venv/lib/python3.9/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /Users/andy/Documents/aig230_NLP/aig230-lab03-andy/.venv/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

## 0) Setup

In [23]:

import re
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, confusion_matrix
import joblib

## 1) A small, realistic dataset (you can replace with your own CSV)

In industry, text often comes with:
- an **ID**
- free-text **description**
- a **label** (category, priority, intent, topic) or a target (churn, fraud, etc.)

Here we create a toy dataset that looks like support tickets / ops incidents.  
Swap this section with a `pd.read_csv(...)` in your own workflows.

In [24]:

data = [
    ("T-001", "VPN keeps disconnecting every 10 minutes on Windows 11 after latest update", "network"),
    ("T-002", "Password reset link is expired and user cannot login to the portal", "auth"),
    ("T-003", "Email delivery delayed, outbound messages queued for hours", "messaging"),
    ("T-004", "Cannot install printer driver, installer fails with error code 1603", "device"),
    ("T-005", "MFA prompt never arrives on mobile app, user stuck at login", "auth"),
    ("T-006", "WiFi signal drops in meeting rooms, access point reboot helps temporarily", "network"),
    ("T-007", "Outlook search not returning results, index seems corrupted", "messaging"),
    ("T-008", "Laptop battery drains fast after BIOS update, power settings unchanged", "device"),
    ("T-009", "Portal shows 500 error when submitting form, happened after deployment", "app"),
    ("T-010", "API requests timing out, latency spike observed in last hour", "app"),
    ("T-011", "User cannot access shared drive, permission denied though in correct group", "auth"),
    ("T-012", "Teams calls have choppy audio, jitter high on corporate network", "network"),
    ("T-013", "Push notifications not working on Android for the app", "app"),
    ("T-014", "Mailbox is full and cannot receive emails, auto-archive not running", "messaging"),
    ("T-015", "Bluetooth mouse not pairing after restart, device shows as unknown", "device"),
    ("T-016", "keyboard broken", "device"),
    ("T-017", "headphone isnt connected", "device"),
    ("T-018", "speaker has no sound", "device"),
    ("T-019", "fan is overheating", "device"),
    ("T-020", "cannot connect to home network", "network"),
    ("T-021", "device is connected to unstable connection", "network"),
    ("T-022", "app is not respond", "app"),
    ("T-023", "game stuttering", "app"),
    ("T-024", "cannot open application", "app"),
    ("T-025", "too many of the same application open", "app"),
]

df = pd.DataFrame(data, columns=["ticket_id", "text", "label"])
df

   ticket_id                                               text      label
0      T-001  VPN keeps disconnecting every 10 minutes on Wi...    network
1      T-002  Password reset link is expired and user cannot...       auth
2      T-003  Email delivery delayed, outbound messages queu...  messaging
3      T-004  Cannot install printer driver, installer fails...     device
4      T-005  MFA prompt never arrives on mobile app, user s...       auth
5      T-006  WiFi signal drops in meeting rooms, access poi...    network
6      T-007  Outlook search not returning results, index se...  messaging
7      T-008  Laptop battery drains fast after BIOS update, ...     device
8      T-009  Portal shows 500 error when submitting form, h...        app
9      T-010  API requests timing out, latency spike observe...        app
10     T-011  User cannot access shared drive, permission de...       auth
11     T-012  Teams calls have choppy audio, jitter high on ...    network
12     T-013  Push notifications not working on Android for ...        app
13     T-014  Mailbox is full and cannot receive emails, aut...  messaging
14     T-015  Bluetooth mouse not pairing after restart, dev...     device
15     T-016                                    keyboard broken     device
16     T-017                           headphone isnt connected     device
17     T-018                               speaker has no sound     device
18     T-019                                 fan is overheating     device
19     T-020                     cannot connect to home network    network
20     T-021         device is connected to unstable connection    network
21     T-022                                 app is not respond        app
22     T-023                                    game stuttering        app
23     T-024                            cannot open application        app
24     T-025              too many of the same application open        app

### Train/test split

In [25]:

X_train, X_test, y_train, y_test = train_test_split(
    df["text"], df["label"], test_size=0.33, random_state=42, stratify=df["label"]
)

print("Train size:", len(X_train))
print("Test size:", len(X_test))

Train size: 16
Test size: 9

## 2) Tokenization basics and normalization (lightweight, practical)

In production pipelines you typically do **minimal, safe normalization**:
- lowercase
- normalize whitespace
- optionally strip obvious punctuation
- keep numbers when they carry meaning (error codes, versions, dates)

Heavy normalization (stemming, aggressive regexes) can hurt when your text includes:
error codes, product names, IDs, or domain terminology.

In [26]:

def simple_normalize(text: str) -> str:
    text = text.lower()
    text = re.sub(r"\s+", " ", text).strip()
    return text

df["text_norm"] = df["text"].map(simple_normalize)
df[["ticket_id","text_norm","label"]].head()

  ticket_id                                          text_norm      label
0     T-001  vpn keeps disconnecting every 10 minutes on wi...    network
1     T-002  password reset link is expired and user cannot...       auth
2     T-003  email delivery delayed, outbound messages queu...  messaging
3     T-004  cannot install printer driver, installer fails...     device
4     T-005  mfa prompt never arrives on mobile app, user s...       auth

## 3) Vocabulary + Document-Term Matrix (DTM) with CountVectorizer

**CountVectorizer** builds:
- a vocabulary (token → column index)
- a sparse matrix where rows are documents and columns are tokens

This is the classic **Document-Term Matrix** representation.

In [27]:

count_vec = CountVectorizer(
    lowercase=True,
    token_pattern=r"(?u)\b\w+\b",  # keeps tokens like "500", "1603", "mfa"
    min_df=1
)

X_train_counts = count_vec.fit_transform(X_train)
X_test_counts  = count_vec.transform(X_test)

print("DTM shape (train):", X_train_counts.shape)
print("Vocabulary size:", len(count_vec.vocabulary_))

DTM shape (train): (16, 107)
Vocabulary size: 107

### Inspect the vocabulary and a single row

In [28]:

# Show a small slice of the vocabulary (token -> index)
vocab_items = sorted(count_vec.vocabulary_.items(), key=lambda x: x[1])[:25]
vocab_items

[('10', 0),
 ('11', 1),
 ('1603', 2),
 ('500', 3),
 ('after', 4),
 ('and', 5),
 ('api', 6),
 ('app', 7),
 ('application', 8),
 ('archive', 9),
 ('arrives', 10),
 ('at', 11),
 ('audio', 12),
 ('auto', 13),
 ('battery', 14),
 ('bios', 15),
 ('broken', 16),
 ('calls', 17),
 ('cannot', 18),
 ('choppy', 19),
 ('code', 20),
 ('connected', 21),
 ('connection', 22),
 ('corporate', 23),
 ('corrupted', 24)]

In [29]:

# Look at a specific document row: non-zero entries (token counts)
row_id = 0
row = X_train_counts[row_id]
inv_vocab = {idx: tok for tok, idx in count_vec.vocabulary_.items()}

nz_cols = row.nonzero()[1]
tokens_counts = sorted([(inv_vocab[c], int(row[0, c])) for c in nz_cols], key=lambda x: -x[1])
tokens_counts[:20]

[('cannot', 1),
 ('install', 1),
 ('printer', 1),
 ('driver', 1),
 ('installer', 1),
 ('fails', 1),
 ('with', 1),
 ('error', 1),
 ('code', 1),
 ('1603', 1)]

## 4) Binary vs Count-based Bag-of-Words

Binary BoW: token present or not (good for short texts and some classification tasks)  
Count BoW: raw frequency (baseline for many pipelines)

Both discard word order.

In [30]:
binary_vec = CountVectorizer(binary=True, token_pattern=r"(?u)\b\w+\b")
X_train_bin = binary_vec.fit_transform(X_train)
#print(x_train_bin.items)
print (X_train_bin.shape)

(16, 107)

## 5) TF-IDF (a refinement, not a replacement)

TF-IDF downweights very common tokens and upweights tokens that are more distinctive.

In industry, TF-IDF with **n-grams** is a strong baseline for:
- ticket routing
- intent detection
- spam detection
- incident clustering

In [31]:

tfidf_vec = TfidfVectorizer(
    ngram_range=(1,3),
    token_pattern = r"(?u)\b\w+\b",
    min_df=1,
    sublinear_tf=True
)

X_train_tfidf = tfidf_vec.fit_transform(X_train)
X_test_tfidf = tfidf_vec.transform(X_test)

In [32]:
print("TF-IDF shape (train):", X_train_tfidf.shape)

TF-IDF shape (train): (16, 319)

## 6) Quick retrieval: 'find similar tickets' with cosine similarity

A very common industry use case is **nearest neighbor retrieval** for:
- deduplication
- suggesting knowledge base articles
- finding similar past incidents

In [ ]:

X_all = tfidf_vec.fit_transform(df["text"])

def search_similar(query: str, top_k: int = 5):
    qv = tfidf_vec.transform([query])
    sims = cosine_similarity(qv, X_all).ravel()
    top_idx = np.argsort(-sims)[:top_k]
    return df.loc[top_idx, ["ticket_id","text","label"]].assign(similarity=sims[top_idx])

search_similar("login mfa not working on phone", top_k=5)

,ticket_id,text,label,similarity
21,T-022,app is not respond,app,0.385023
12,T-013,Push notifications not working on Android for ...,app,0.225807
4,T-005,"MFA prompt never arrives on mobile app, user s...",auth,0.114204

In [ ]:
search_similar("device not working", top_k=3)
#makes sense devices not working

,ticket_id,text,label,similarity
12,T-013,Push notifications not working on Android for ...,app,0.291741
14,T-015,"Bluetooth mouse not pairing after restart, dev...",device,0.138281
20,T-021,device is connected to unstable connection,network,0.117465

In [ ]:
search_similar("network issue", top_k=3)
#issues with network

,ticket_id,text,label,similarity
19,T-020,cannot connect to home network,network,0.268996
11,T-012,"Teams calls have choppy audio, jitter high on ...",network,0.172693
2,T-003,"Email delivery delayed, outbound messages queu...",messaging,0.000000

In [ ]:
search_similar("app does not work", top_k=3)
#problems with app

,ticket_id,text,label,similarity
21,T-022,app is not respond,app,0.385023
12,T-013,Push notifications not working on Android for ...,app,0.225807
4,T-005,"MFA prompt never arrives on mobile app, user s...",auth,0.114204

## 7) Classification baseline (Logistic Regression)

For text classification, a strong baseline is:

**TF-IDF → Linear model (LogReg / Linear SVM)**

This is fast, reliable, easy to explain, and often hard to beat without deep learning.

In [34]:

clf = LogisticRegression(max_iter=2000)

pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(
        ngram_range=(1,3),
        token_pattern=r"(?u)\b\w+\b",
        sublinear_tf=True
    )),
    ("model", clf)
])

pipeline.fit(X_train, y_train)
pred = pipeline.predict(X_test)

print(classification_report(y_test, pred))
print("Confusion matrix:\n", confusion_matrix(y_test, pred))

              precision    recall  f1-score   support

         app       0.22      1.00      0.36         2
        auth       0.00      0.00      0.00         1
      device       0.00      0.00      0.00         3
   messaging       0.00      0.00      0.00         1
     network       0.00      0.00      0.00         2

    accuracy                           0.22         9
   macro avg       0.04      0.20      0.07         9
weighted avg       0.05      0.22      0.08         9

Confusion matrix:
 [[2 0 0 0 0]
 [1 0 0 0 0]
 [3 0 0 0 0]
 [1 0 0 0 0]
 [2 0 0 0 0]]

/Users/andy/Documents/aig230_NLP/aig230-lab03-andy/.venv/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/andy/Documents/aig230_NLP/aig230-lab03-andy/.venv/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/andy/Documents/aig230_NLP/aig230-lab03-andy/.venv/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

## 8) Production pattern: HashingVectorizer (no stored vocab)

In production, you may need:
- constant memory usage
- privacy (no vocabulary inspection)
- streaming support
- easier deployment across services

**HashingVectorizer** avoids building a vocabulary. Tradeoff: collisions.

In [35]:

hash_pipe = Pipeline([
    ("hash", HashingVectorizer(
        n_features=2**18,        # tune for your scale
        alternate_sign=False,    # makes features more interpretable for linear models
        ngram_range=(1,3),
        token_pattern=r"(?u)\b\w+\b"
    )),
    ("model", LogisticRegression(max_iter=2000))
])

hash_pipe.fit(X_train, y_train)
pred_hash = hash_pipe.predict(X_test)
print(classification_report(y_test, pred_hash))

              precision    recall  f1-score   support

         app       0.22      1.00      0.36         2
        auth       0.00      0.00      0.00         1
      device       0.00      0.00      0.00         3
   messaging       0.00      0.00      0.00         1
     network       0.00      0.00      0.00         2

    accuracy                           0.22         9
   macro avg       0.04      0.20      0.07         9
weighted avg       0.05      0.22      0.08         9

/Users/andy/Documents/aig230_NLP/aig230-lab03-andy/.venv/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/andy/Documents/aig230_NLP/aig230-lab03-andy/.venv/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/andy/Documents/aig230_NLP/aig230-lab03-andy/.venv/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

## 9) Save and load the model (typical deployment step)

In [36]:


model_path = "week3_text_representation_model.joblib"
joblib.dump(pipeline, model_path)

loaded = joblib.load(model_path)
loaded.predict(["portal returns 500 error after deploy"])

array(['app'], dtype=object)

## Exercises (do these during lab)
1) Add 10 more tickets to `data` with realistic wording and labels. Re-train and compare results.  
2) Try `ngram_range=(1,3)` and observe what changes.  
3) For retrieval, test at least 3 queries and explain why the top result makes sense.  
4) Replace the dataset with a CSV you create (columns: `text`, `label`) and rerun the notebook.